require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'kandy_sample_reactnative_ios' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'KandyCPaaSMobileSDK' , '2.14.0'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
end